development:
  adapter: postgresql
  database: bomb_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bomb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bomb_prod
  pool: 5
  timeout: 5000
