# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf4f4b16153f1434aea87d01db88c4eb3f676bb46aaf2550c009b207bc0fcd76c86b766c84e0fbf32dc77c0102f372199653ae4ee385f39c1a5480b7e2b8498

test:
  secret_key_base: 61c91315673d97baa5e18cadc84eab2ee5610fc1d32a732e8ff04a30c55205933469c89a797b8e77b4138c9852ea12708f1795e5a682313c845fc20be08f4219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
